# Copyright (C) 2020, Lawrence Berkeley National Laboratory.                
# All rights reserved.                                                      
#                                                                           
# This file is part of Taskworks. The full Taskworks copyright notice,      
# including terms governing use, modification, and redistribution, is       
# contained in the file COPYING at the root of the source code distribution 
# tree.                                                                     


/* Test engine*/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    # Install autotools
    - apt update && apt -y install make autoconf automake libtool
    - autoconf --version
    - automake --version
    - libtool --version
    # Install MPI
    - apt -y install mpich3
    # Install OpenPA
    - git clone https://github.com/pmodels/openpa.git 
    - pushd  openpa && ./configure && make && make install && popd 
    # Install Argobots
    - git clone https://github.com/pmodels/argobots.git
    - pushd  argobots && ./configure && make && make install && popd
  script:
    - autoreconf -i
    - /configure --with-opa=yes --enable-parallel --with-argobots=yes
  #artifacts:
    #paths:
      #- mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - make check
