# Copyright (C) 2020, Lawrence Berkeley National Laboratory.                
# All rights reserved.                                                      
#                                                                           
# This file is part of Taskworks. The full Taskworks copyright notice,      
# including terms governing use, modification, and redistribution, is       
# contained in the file COPYING at the root of the source code distribution 
# tree.                                                                     

variables:
  SCHEDULER_PARAMETERS: "-C haswell --qos=debug -N1 -t 00:30:00"

stages:
  - build
  - test

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    # Install autotools
    # Don't work on Cori runners, use default
    # - apt update && apt -y install make autoconf automake libtool
    - autoconf --version
    - automake --version
    - libtool --version
    # Install MPI
    # Don't work on Cori runners, use default
    # - apt -y install mpich3
    # Make dir to build dependencies
    - mkdir tw_deps
    # Install OpenPA
    - git clone -b v1.0.4 https://github.com/pmodels/openpa.git 
    - pushd  openpa && ./autogen.sh && ./configure --prefix=${PWD}/../tw_deps && make -j 64 && make -j 64 install && popd 
    # Install Argobots
    - git clone -b v1.0 https://github.com/pmodels/argobots.git 
    - pushd argobots && ./autogen.sh && ./configure --prefix=${PWD}/../tw_deps && make -j 64 && make -j 64  install && popd
  script:
    - autoreconf -i
    - ./configure --with-opa=${PWD}/tw_deps --enable-parallel --with-argobots=${PWD}/tw_deps
    - make -j 64 
  tags:
    - cori
  cache:
    paths:
      - "./*"
  artifacts:
    paths:
      # Autotool metadata will be corrupted by stage init, save the entire repo as artifact
      # - "./"

# run tests using the binary built before
test:
  stage: test
  script:
    # - autoreconf -i
    # - ./configure --with-opa=${PWD}/tw_deps --enable-parallel --with-argobots=${PWD}/tw_deps
    - make -j 64 tests
    - make check
  tags:
    - cori