dist: bionic

language: c

compiler:
	- gcc

branches:
	only:
		- master

git:
  submodules: false

# Use gcc-9
# matrix:
	# include:
    	# - os: linux
		# addons:
        	# apt:
          		# sources:
            		# - ubuntu-toolchain-r-test
			# packages:
				# - g++-9
		# env:
			# - MATRIX_EVAL="CC=gcc-0 && CXX=g++-9"

before_install:
	- test -n $CC && unset CC

install: make 
	# Toolchain
	- sudo apt-get install --only-upgrade autoconf
	- sudo apt-get install --only-upgrade automake
	- sudo apt-get install --only-upgrade libtool

	# MPI
	- sudo apt-get install -y mpich3

	# OpenPA
	- git clone https://github.com/pmodels/openpa.git
	- pushd openpa && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd

	# Show dep version
	- autoconf --version
	- automake --version
	- libtool --version
	- mpiexec --version
	- g++ --version

script:
	- ./configure
	- make -j 4
	- make check

after_success:
	- make clean

after_failure:
	- cat ./config.log
	- cat test/basic/*.log